encyclopedia/urls.py
from django.urls import path

from . import views

app_name = "wiki"

urlpatterns = [
    path("", views.index, name="index"),
    path("search", views.search, name="serachentry"),
    path("add", views.add, name="add"),
    path("create", views.create, name="create"),
    path("edit", views.edit, name="edit"),
    path("random", views.random_page, name="random"),
    path("afteredit", views.afteredit, name="afteredit"),
    path("<str:name>", views.select, name="selectentry")
]

wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

encyclopedia/models.py
from django.db import models

# Create your models here.

encyclopedia/views.py
from django.shortcuts import render
from markdown2 import Markdown
from . import util
import random


app_name="wiki"

# Render the default page that shows the list of entries
def index(request):
    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries()
    })

# Render particular page that the user search fo it the search box
def search(request):
    if request.method == 'GET':
        # Define an empty list
        search = []
        entry = request.GET['q']

        # Search if the inputed char in any entry name
        for x in util.list_entries():
            if entry.upper() in x.upper():
                search.append(x)
    if search:            
        return render(request, "encyclopedia/index.html", {
            "entries": search
            })
    else:
        return render(request, "encyclopedia/notexist.html", {
            "content": "Page Not Found"
        })

# Render any page that select from the shown list
def select(request, name):
    try:
        # Convert the markdown input to html content
        output = Markdown().convert(util.get_entry(name))
        return render(request, "encyclopedia/title.html", {
            "title": name, "content": output
        })
    except:
        return render(request, "encyclopedia/notexist.html")


def add(request):
    return render(request, "encyclopedia/newpage.html")


def create(request):
    if request.method == 'POST':
        # Handel every entry by the user by it's own
        title = request.POST['title']
        content = request.POST['content']

    # If the page is already exist render this page
    if title in util.list_entries():
        return render(request, "encyclopedia/notexist.html", {
            "content": "Encyclopedia Already Exist"
        })
    else:
        # Save the title and the content using the save function from util file
        util.save_entry(title, content)

        markdowner = Markdown()
        output = markdowner.convert(util.get_entry(title))
        return render(request, "encyclopedia/title.html", {
            "title": title, "content": output
        })

def edit(request):
    if request.method == 'POST':
        edit_title = request.POST['title']
        edit_content = util.get_entry(request.POST['title'])

        return render(request, "encyclopedia/edit.html", {
        'title': edit_title, 'content': edit_content
        })


def random_page(request):
    # Return the name of an entry
    randompage = random.choice(util.list_entries())

    # Get the content of the page that randomly picked from random function
    output = Markdown().convert(util.get_entry(randompage))
    return render(request, "encyclopedia/title.html", {
        "title": randompage, "content": output
    })

def afteredit(request):
    if request.method == 'POST':
        old_title = request.POST["oldtitle"]
        new_title = request.POST["newtitle"]
        new_content = request.POST["newcontent"]

        util.save_entry(old_title, new_content)

    output = Markdown().convert(util.get_entry(old_title))
    return render(request, "encyclopedia/title.html", {
        'title': old_title, 'content': output
    })

encyclopedia/templates/encyclopedia/edit.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Edit
{% endblock %}

{% block body %}
    <h1>Edit Encyclopedia</h1>

    <form action="afteredit" method="POST">
        {% csrf_token %}
        <label for="title">Title of the Encyclopedia:</label></br>
        <input type="text" name="newtitle" id="title" value="{{ title }}"></br>
        <input type="text" name="oldtitle" value="{{ title }}" hidden>

        <label for="content">Content of the Encyclopedia:</label></br>
        <textarea id="content" name="newcontent" style="height: 300px;">{{ content }}</textarea></br>

        <input type="submit" value="Save">
    </form>
{% endblock %}

encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>

    <ul>
        {% for entry in entries %}
            <li><a href="{{ entry }}">{{ entry }}</a></li>
        {% endfor %}
    </ul>

{% endblock %}

encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form action="/search">
                    <input class="search" type="text" name="q" placeholder="Search Encyclopedia">
                </form>
                <div>
                    <a href="{% url 'wiki:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'wiki:add' %}">Create New Page</a>
                </div>
                <div>
                    <a href="{% url 'wiki:random' %}">Random Page</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

encyclopedia/templates/encyclopedia/newpage.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    New Encyclopedia
{% endblock %}

{% block body %}
    <h1>Creat New Page:</h1>

    <form action="/create" method="POST">
        {% csrf_token %}
        <label for="title">Encyclopedia Title:</label></br>
        <input type="text" id="title" name="title" placeholder="Encyclopedia Title"></br>

        <label for="body">Content:</label></br>
        <textarea id="body" placeholder="The content of the new encyclopedia" style="height: 400px;" name="content"></textarea></br>

        <input type="submit" value="Creat">
    </form>
{% endblock %}

encyclopedia/templates/encyclopedia/notexist.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    encyclopedia
{% endblock %}

{% block body %}

    {{content}}

{% endblock %}

encyclopedia/templates/encyclopedia/title.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {{ title | safe }}
{% endblock %}

{% block body %}
    {{ content | safe }}
    <form action="{% url 'wiki:edit' %}" method="POST">
        {% csrf_token %}
        <input type="text" name="title" hidden value={{ title }}>
        <button>Edit</button>
    </form>

{% endblock %}